trackers = ["udp://tracker.coppersurfer.tk:6969", "udp://tracker.leechers-paradise.org:6969/announce", "udp://tracker.opentrackr.org:1337/announce","udp://tracker.cyberia.is:6969/announce","udp://tracker.torrent.eu.org:451"]
waitTime = "250ms"
logInterval = "1h"

categories = { 0 = "2880h", 1 = "1440h", 3 = "720h", 10 = "96h", 60 = "48h", 100 = "24h", 500 = "8h", 1000 = "2h"}
